Repository educata/iswavle, pull requests merged in 2025-08, with the labels that each got.

#169 feat: sitemap generator
  angular.json
  package.json
  prerender/generate-sitemap.ts
  src/index.html
  src/robots.txt
  src/sitemap.xml
Labels: enhancement

#143 docs: client side tools
  src/app/shared/consts/doc-navigation.ts
  src/app/shared/consts/doc-navigation/client-side-tools.ts
  src/app/shared/consts/doc-navigation/index.ts
  src/content/guides/client-side-tools/overview.md
  src/content/guides/client-side-tools/package-management.md
  src/content/guides/typescript/tsc.md
Labels: article request

#173 fix: hyperlinks
  src/content/exercises/remove-primitive-duplicates-from-array/description.md
  src/content/guides/angular/authentication.md
  src/content/guides/angular/authentication/can-activate.md
  src/content/guides/angular/authentication/jwt-authentication.md
  src/content/guides/angular/control-flow.md
  src/content/guides/angular/data-binding.md
  src/content/guides/angular/data-binding/property-and-attribute-binding.md
  src/content/guides/angular/data-binding/two-way-binding.md
  src/content/guides/angular/dependency-injection.md
  src/content/guides/angular/dependency-injection/di-in-angular.md
  src/content/guides/angular/directives.md
  src/content/guides/angular/directives/creating-directive.md
  src/content/guides/angular/directives/structural-directives.md
  src/content/guides/angular/forms.md
  src/content/guides/angular/forms/validation.md
  src/content/guides/angular/http.md
  src/content/guides/angular/internationalization.md
  src/content/guides/angular/internationalization/angular-i18n.md
  src/content/guides/angular/internationalization/ngx-translate.md
  src/content/guides/angular/internationalization/summary.md
  src/content/guides/angular/introduction.md
  src/content/guides/angular/introduction/creating-component.md
  src/content/guides/angular/introduction/getting-started.md
  src/content/guides/angular/introduction/interpolation-data-binding.md
  src/content/guides/angular/ng-modules.md
  src/content/guides/angular/pipes.md
  src/content/guides/angular/routing.md
  src/content/guides/angular/routing/dynamic-routes.md
  src/content/guides/angular/routing/dynamic-routes/route-params.md
  src/content/guides/angular/rxjs.md
  src/content/guides/angular/rxjs/observable-stream.md
  src/content/guides/angular/rxjs/operators.md
  src/content/guides/angular/standalone.md
  src/content/guides/angular/state-management/adding-data-to-state.md
  src/content/guides/angular/state-management/initial-setup.md
  src/content/guides/angular/state-management/initializing-state.md
  src/content/guides/angular/state-management/loading-state-and-error.md
  src/content/guides/angular/state-management/update-and-delete.md
  src/content/guides/angular/tests.md
  src/content/guides/client-side-tools.md
  src/content/guides/javascript/array.md
  src/content/guides/javascript/canvas/basic-animations.md
  src/content/guides/javascript/canvas/using-images.md
  src/content/guides/javascript/dom/elements-manipulation.md
  src/content/guides/javascript/error-handling.md
  src/content/guides/javascript/function.md
  src/content/guides/javascript/loops.md
  src/content/guides/typescript/class.md
Labels: editing article

#109 docs: REST API
  src/app/shared/consts/doc-navigation/js.ts
  src/assets/images/insomnia.png
  src/assets/images/postman.png
  src/content/examples/guides/javascript-fetch-shop/index.html
  src/content/examples/guides/javascript-fetch-shop/main.js
  src/content/examples/guides/javascript-fetch-shop/style.css
  src/content/examples/guides/javascript-generate-qr/index.html
  src/content/examples/guides/javascript-generate-qr/main.js
  src/content/examples/guides/javascript-generate-qr/style.css
  src/content/examples/guides/javascript-products-simple-example/index.html
  src/content/examples/guides/javascript-products-simple-example/main.js
  src/content/examples/guides/javascript-products-simple-example/style.css
  src/content/examples/guides/javascript-random-quote/index.html
  src/content/examples/guides/javascript-random-quote/main.js
  src/content/examples/guides/javascript-random-quote/style.css
  src/content/guides/javascript/rest-api.md
  src/content/guides/javascript/rest-api/api-documentations.md
  src/content/guides/javascript/rest-api/fetch.md
  src/content/guides/javascript/rest-api/json-xml.md
  src/content/guides/javascript/rest-api/practice.md
  src/content/guides/javascript/rest-api/summary.md
  src/content/guides/javascript/rest-api/xhr.md
Labels: article request
